environment:
  SSL_CERT_FILE: "C:\\OpenSSL\\cacert.pem"

  matrix:
      - TARGET: x86_64-pc-windows-msvc
        BITS: 64
        OPENSSL_VERSION: 1_1_0e
        MSYS2: 1
        OPENSSL_DIR: C:\OpenSSL
      - TARGET: i686-pc-windows-gnu
        BITS: 32
        OPENSSL_VERSION: 1_1_0e
        MSYS2: 1
install:
  - ps: Start-FileDownload "http://slproweb.com/download/Win${env:BITS}OpenSSL-${env:OPENSSL_VERSION}.exe"
  - Win%BITS%OpenSSL-%OPENSSL_VERSION%.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"
  - ps: Start-FileDownload "https://curl.haxx.se/ca/cacert.pem" -FileName "C:\OpenSSL\cacert.pem"

  # Install Rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%

  # Run tests
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test

cache:
  - target
  - C:\Users\appveyor\.cargo\registry
