[package]

name = "shadowsocks-rust"
version = "0.9.5"
authors = ["Y. T. CHUNG <zonyitoo@gmail.com>"]

[lib]

name = "shadowsocks"

[features]

default = [
    "cipher-aes-cfb",
    "cipher-aes-ofb",
    "cipher-bf-cfb",
    "cipher-cast5-cfb",
    "cipher-des-cfb",
    "cipher-rc2-cfb",
    "cipher-rc4",

    "enable-udp",
]

cipher-aes-cfb = []
cipher-aes-ofb = []
cipher-aes-ctr = []
cipher-bf-cfb = []
cipher-camellia-cfb = []
cipher-cast5-cfb = []
cipher-des-cfb = []
cipher-idea-cfb = []
cipher-rc2-cfb = []
cipher-rc4 = []
cipher-seed-cfb = []

enable-udp = []
enable-green = ["green", "rustuv"]

[[bin]]

name = "sslocal"
path = "src/bin/local.rs"

[[bin]]

name = "ssserver"
path = "src/bin/server.rs"

[dependencies.green]
optional = true
git = "https://github.com/alexcrichton/green-rs.git"

[dependencies.rustuv]
optional = true
git = "https://github.com/alexcrichton/green-rs.git"

[dependencies.collect]
git = "https://github.com/Gankro/collect-rs.git"

#[dependencies.log]
#log = "0.1.4"
