[package]
name = "shadowsocks-rust"
version = "1.6.6"
authors = ["Y. T. CHUNG <zonyitoo@gmail.com>"]
description = "shadowsocks is a fast tunnel proxy that helps you bypass firewalls."
repository = "https://github.com/zonyitoo/shadowsocks-rust"
documentation = "https://docs.rs/shadowsocks-rust"
keywords = ["shadowsocks", "proxy", "socks", "socks5", "firewall"]
license = "MIT"

[lib]
name = "shadowsocks"

[[bin]]
name = "sslocal"
path = "src/bin/local.rs"

[[bin]]
name = "ssserver"
path = "src/bin/server.rs"

[[bin]]
name = "ssurl"
path = "src/bin/ssurl.rs"

[dependencies]
log = "0.3"
byteorder = "1.1"
rand = "0.3"
time = "0.1"
clap = "2"
env_logger = "0.4"
openssl = "0.9"
lru_time_cache = "0.6"
libc = "0.2"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
lazy_static = "0.2"
serde_json = "1.0"
base64 = "0.6"
netdb = "0.1"
bytes = "0.4"
scoped-tls = "0.1"
ring = "0.11"
md-5 = "0.5"
digest = "0.6"
typenum = "1.9"
qrcode = { version = "0.4", default-features = false }
subprocess = "0.1"
serde_urlencoded = "0.5"
url = "1.5"
byte_string = "1.0"
libsodium-ffi = "0.1"

[target.'cfg(unix)'.dependencies]
tokio-signal = "0.1"
