[package]

name = "shadowsocks-rust"
version = "0.9.0"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]

[lib]

name = "shadowsocks"

[features]
default = [
    "cipher-aes-cfb",
    "cipher-aes-ofb",
    "cipher-bf-cfb",
    "cipher-cast5-cfb",
    "cipher-des-cfb",
    "cipher-rc2-cfb",
    "cipher-rc4",
]

cipher-aes-cfb = []
cipher-aes-ofb = []
cipher-aes-ctr = []
cipher-bf-cfb = []
cipher-camellia-cfb = []
cipher-cast5-cfb = []
cipher-des-cfb = []
cipher-idea-cfb = []
cipher-rc2-cfb = []
cipher-rc4 = []
cipher-seed-cfb = []

[[bin]]

name = "sslocal"
path = "src/bin/local.rs"

[[bin]]

name = "ssserver"
path = "src/bin/server.rs"
