[package]
name = "shadowsocks-rust"
version = "1.7.1"
authors = ["Y. T. CHUNG <zonyitoo@gmail.com>"]
description = "shadowsocks is a fast tunnel proxy that helps you bypass firewalls."
repository = "https://github.com/zonyitoo/shadowsocks-rust"
documentation = "https://docs.rs/shadowsocks-rust"
keywords = ["shadowsocks", "proxy", "socks", "socks5", "firewall"]
license = "MIT"
edition = "2018"

[lib]
name = "shadowsocks"

[[bin]]
name = "sslocal"
path = "src/bin/local.rs"

[[bin]]
name = "ssserver"
path = "src/bin/server.rs"

[[bin]]
name = "ssurl"
path = "src/bin/ssurl.rs"

[[bin]]
name = "ssdns"
path = "src/bin/ssdns.rs"

[profile.release]
lto = true

[features]
default = ["sodium", "rc4", "aes-cfb", "aes-ctr"]
sodium = ["libsodium-ffi"]
rc4 = ["openssl"]
aes-cfb = ["openssl"]
aes-ctr = ["openssl"]
single-threaded = []

[dependencies]
log = "0.4"
byteorder = "1.3"
rand = "0.7"
time = "0.1"
clap = "2.33"
env_logger = "0.6"
openssl = { version = "0.10", optional = true }
libc = "0.2"
futures = "0.1"
tokio-io = "0.1"
tokio = "0.1"
json5 = "0.2"
base64 = "0.10"
bytes = "0.4"
ring = "0.14"
md-5 = "0.8"
digest = "0.8"
typenum = "1.10"
qrcode = { version = "0.10", default-features = false }
serde_urlencoded = "0.5"
serde = { version = "1.0", features = ["derive"] }
url = "2.0"
byte_string = "1.0"
libsodium-ffi = { version = "0.1", optional = true }
miscreant = { version = "0.4", optional = true }
lru-cache = "0.1"
dns-parser = "0.8"
trust-dns-resolver = { version = "0.11", features = ["dns-over-rustls", "dns-over-https-rustls"] }
spin = { version = "0.5", default-features = false }
tokio-process = "0.2"

[target.'cfg(unix)'.dependencies]
tokio-signal = "0.2"

[target.'cfg(windows)'.dependencies]
tokio-signal = "0.2"
