[package]
name = "shadowsocks-rust"
version = "1.0.1"
authors = ["Y. T. CHUNG <zonyitoo@gmail.com>"]
description = "shadowsocks is a fast tunnel proxy that helps you bypass firewalls."
repository = "https://github.com/zonyitoo/shadowsocks-rust"
documentation = "https://docs.rs/shadowsocks-rust"
keywords = ["shadowsocks", "proxy", "socks", "socks5", "firewall"]
license = "MIT"

[lib]

name = "shadowsocks"

[features]

default = [
    "cipher-aes-cfb",
    "cipher-rc4",

    "cipher-chacha20",
    "cipher-salsa20",
]

cipher-aes-cfb = []
cipher-rc4 = []
cipher-chacha20 = []
cipher-salsa20 = []

[[bin]]
name = "sslocal"
path = "src/bin/local.rs"

[[bin]]
name = "ssserver"
path = "src/bin/server.rs"

[[bin]]
name = "ssurl"
path = "src/bin/ssurl.rs"

[dependencies]
rustc-serialize = "0.3"
log = "0.3"
byteorder = "0.5"
rand = "0.3"
time = "0.1"
clap = "2"
qrcode = "0.2"
env_logger = "0.3"
rust-crypto = "0.2"
ip = "1"
openssl = "0.8"
lru-cache = "0.1"
libc = "0.2"
hyper = "0.9"
url = "1.2"
httparse = "1.1"
futures = "0.1"
futures-cpupool = "0.1"
tokio-core = "0.1"
net2 = "0.2"
num_cpus = "1.1"
lazy_static = "0.2"
