[package]

name = "shadowsocks-rust"
version = "0.9.7"
authors = ["Y. T. CHUNG <zonyitoo@gmail.com>"]

[lib]

name = "shadowsocks"

[features]

default = [
    "cipher-aes-cfb",
    "cipher-aes-ofb",
    "cipher-bf-cfb",
    "cipher-cast5-cfb",
    "cipher-des-cfb",
    "cipher-rc2-cfb",
    "cipher-rc4",

    "cipher-chacha20",
    "cipher-salsa20",

    "enable-udp",
]

cipher-aes-cfb = []
cipher-aes-ofb = []
cipher-aes-ctr = []
cipher-bf-cfb = []
cipher-camellia-cfb = []
cipher-cast5-cfb = []
cipher-des-cfb = []
cipher-idea-cfb = []
cipher-rc2-cfb = []
cipher-rc4 = []
cipher-seed-cfb = []
cipher-chacha20 = ["enable-sodium"]
cipher-salsa20 = ["enable-sodium"]

enable-udp = []
enable-sodium = ["libsodium-sys"]

[[bin]]

name = "sslocal"
path = "src/bin/local.rs"

[[bin]]

name = "ssserver"
path = "src/bin/server.rs"

[dependencies]
collect = "*"
rustc-serialize = "*"
log = "*"
byteorder = "*"

[dependencies.libsodium-sys]
git = "https://github.com/zonyitoo/libsodium-sys.git"
optional = true
